sudo: required
services:
  - docker
language: python
python: 3.7

env:
  global:
    - IMAGE_TAG=amd64-4.2.x
    - IMAGE_NAME=emiljacero/powerdns-auth-docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --tag "$IMAGE_NAME" .
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:amd64-latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${IMAGE_TAG}"
  - docker push "${IMAGE_NAME}:amd64-latest" && docker push "${IMAGE_NAME}:${IMAGE_TAG}"

after_script:
  - docker images
