version: '3.1'
    
volumes:
  db-pdns-auth:
  pdns-auth:

networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: "192.168.254.0/24"

services:
  db-pdns-auth:
    container_name: db-pdns-auth
    image: postgres:11
    restart: always
    networks:
      - dns
    environment:
      TZ: Europe/Stockholm
      POSTGRES_USER: pdns
      POSTGRES_PASSWORD: supersecretpsqlpw
      POSTGRES_DB: pdns
    volumes:
      - "db-pdns-auth-master:/var/lib/postgresql/data"

  pdns-auth:
    container_name: pdns-auth
    build:
        context: .
        dockerfile: Dockerfile
        args:
          PDNS_VERSION: 44
    image: emiljacero/powerdns-auth-docker:amd64-4.4.x
    restart: always
    depends_on:
      - db-pdns-auth
    networks:
      - dns
    environment:
      TZ: Europe/Stockholm
      LOG_LEVEL: DEBUG
      ENV_PDNS_PGSQL_HOST: db-pdns-auth-master
      ENV_PDNS_PGSQL_PORT: 5432
      ENV_PDNS_PGSQL_DBNAME: pdns
      ENV_PDNS_PGSQL_USER: pdns
      ENV_PDNS_PGSQL_PASSWORD: supersecretpsqlpw
      ENV_PDNS_DNSSEC: "yes"
      ENV_PDNS_API_PORT: 8001
      ENV_PDNS_API_KEY: supersecretapikey
      ENV_PDNS_AXFR_IPS: 0.0.0.0 # IPs of slaves
      ENV_PDNS_MODE: MASTER
    ports:
      - 8001:8001/tcp
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - "pdns-auth:/var/run/pdns"